### PR TITLE
Style single

### PR DESCRIPTION
**Pull request by varffs**

### CODE REVIEW

**Comment by mixcas** [comment]
i't doesn't look right for me



https://github.com/interglobalvision/8106-tv/blob/master/css/site.styl#L132
maybe this needs overwrite?

**Comment by mixcas** [comment]
This seems all fine but what about WP Generated classes?

https://codex.wordpress.org/CSS#WordPress_Generated_Classes

**Comment by mixcas** [comment]
I thought the first image was _the post thumbnail_
no?

**Comment by varffs** [comment]
I think you should merge this. Refined content styling is something that can happen a bit later. This is the basic level for single

**Pull request merged**
