### PR TITLE
Feat slider

### PR DESCRIPTION
**Pull request by mixcas**
add slider code and lib

with caption:

on hover without caption:

touch devices:

idk if the caption needs more styling (?)

### CODE REVIEW

**Comment by varffs** [comment]
screen shot 2016-03-29 at 18 39 31

No gallery size image declared in functions.php so seems to take size from the first image only and therefor crops and overlays the captions when images have larger heights

**Comment by varffs** [comment]
Also i thought you were going to remove the arrows?

**Comment by varffs** [comment]
only just realised you used Cycle rather than Swiper? Thats fine rly but I think we are prefering Swiper as number 1 js gallery plug

**Comment by varffs** [comment]
Can we just get rid of all arrows and make the next/prev click area the full half of the gallery on each side. With the height changing now it moves the arrows so you have to move the mouse to click thru a gallery. The arrows are ugly too

**Comment by varffs** [comment]
Also while your at it can you remove the space between the index and length in the gallery captions so it is just `2/5:`

**Comment by mixcas** [comment]
@varffs 

i didnt wanted to have to rewrite the gallery to match swiper, gotta make it in the boiler tho

i dont think having only the counter is enough hint to know its a slider, also they ask me if we could always show the arrows…

also the height doesnt really change cuz of the image size used

i like the spaces next to the `/` but ok

**Comment by varffs** [comment]
The height does change it literally happened on my local after regenerating thumbnails.

The compromise then could be 50% click areas on both sides and smaller arrows always shown in black without the animation?

**Comment by mixcas** [comment]
what about dark photos?

**Comment by varffs** [comment]
the arrows just wont be so prominent thats fine

**Pull request merged**
